### ISSUE TITLE
can i add own mac portal on it ?

### ISSUE THREAD

**Issue by rajat-ankel** [Jitendraunatti/jiotv-be#3]
I only have 

Portal:
Mac:

how can i get token

**Comment by Jitendraunatti** [comment]
you need to write code for that

**Comment by rajat-ankel** [comment]
code to get token from url and mac?

**Comment by Jitendraunatti** [comment]
Yes, you can get it, but sometimes it doesn't work. You need the URL, MAC device ID 1 and 2, and the serial number.
