### ISSUE TITLE
Logos not showing

### ISSUE THREAD

**Issue by gitsheikhgit** [Jitendraunatti/jiotv-be#4]
Logo file link is in the playlist.php but logos do not show up on any of the channels.

**Comment by Jitendraunatti** [comment]
Yes, the main source doesn't have a logo.

**Comment by gitsheikhgit** [comment]
Ok thanks

**Comment by gitsheikhgit** [comment]
I installed it on a Proxmox VM . I used Ubuntu 22.4 for this setup; I installed XAMPP webserver. Downloaded jiotv-be.zip and jazztv.zp to htdocs folder and unzipped both files in respective folders. 

All working but channel loading time is very long. Is it normal or is it because of my VM?
I gave it 1 processor and 1024mb memory. 
Is it good enough?

**Comment by Jitendraunatti** [comment]
yes it is normal
